repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    # Git style
    - id: check-added-large-files

    # Common errors
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.66.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --init-args=-backend=false
        - --args=-no-color
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        - --args=--config=.terraform-docs.yml
